# Use root/root as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0    
    volumes:  # volume
      - ./mysql-data:/var/lib/mysql
    container_name: mysqlserver
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:    
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
